### ISSUE TITLE
2022.6.5版本报错了（Home Assistant Core 2022.6.6）

### ISSUE THREAD

**Issue by nesror** [shaonianzhentan/ha_file_explorer#39]
Logger: aiohttp.server
Source: custom_components/ha_file_explorer/file_api.py:58
Integration: 文件浏览器 ([documentation](https://github.com/shaonianzhentan/ha_file_explorer))
First occurred: 15:50:41 (2 occurrences)
Last logged: 15:51:59

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/config/custom_components/ha_file_explorer/http_api.py", line 34, in get
    data = get_dir_list(path)
  File "/config/custom_components/ha_file_explorer/file_api.py", line 30, in get_dir_list
    hashInfo['size_name'] = format_byte(hashInfo['size'])
  File "/config/custom_components/ha_file_explorer/file_api.py", line 58, in format_byte
    return "%.2f %s" %(number*1.0/scale,lable)
NameError: name 'lable' is not defined

另外 文件夹 和 文件的列表都是空的

**Comment by shaonianzhentan** [comment]
问题修复了，你重新下载dev的版本再看看

**Comment by nesror** [comment]
> 问题修复了，你重新下载dev的版本再看看

正常了
